# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NetWorkMonitorGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NetWorkMonitor(object):
    def setupUi(self, NetWorkMonitor):
        NetWorkMonitor.setObjectName("NetWorkMonitor")
        NetWorkMonitor.resize(380, 140)
        NetWorkMonitor.setMaximumSize(QtCore.QSize(380, 140))
        NetWorkMonitor.setAccessibleName("")
        self.groupBox_2 = QtWidgets.QGroupBox(NetWorkMonitor)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 0, 360, 140))
        self.groupBox_2.setMinimumSize(QtCore.QSize(360, 140))
        self.groupBox_2.setMaximumSize(QtCore.QSize(360, 140))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.startBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.startBtn.setObjectName("startBtn")
        self.gridLayout_2.addWidget(self.startBtn, 7, 0, 1, 1)
        self.checkLogBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.checkLogBtn.setObjectName("checkLogBtn")
        self.gridLayout_2.addWidget(self.checkLogBtn, 7, 2, 1, 1)
        self.host_fixture1 = QtWidgets.QCheckBox(self.groupBox_2)
        self.host_fixture1.setChecked(True)
        self.host_fixture1.setObjectName("host_fixture1")
        self.gridLayout_2.addWidget(self.host_fixture1, 1, 0, 1, 1)
        self.host_gh = QtWidgets.QCheckBox(self.groupBox_2)
        self.host_gh.setChecked(True)
        self.host_gh.setObjectName("host_gh")
        self.gridLayout_2.addWidget(self.host_gh, 1, 2, 1, 1)
        self.stopBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.stopBtn.setObjectName("stopBtn")
        self.gridLayout_2.addWidget(self.stopBtn, 7, 1, 1, 1)
        self.host_fixture2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.host_fixture2.setChecked(True)
        self.host_fixture2.setObjectName("host_fixture2")
        self.gridLayout_2.addWidget(self.host_fixture2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 8, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 2, 1, 1)

        self.retranslateUi(NetWorkMonitor)
        QtCore.QMetaObject.connectSlotsByName(NetWorkMonitor)

    def retranslateUi(self, NetWorkMonitor):
        _translate = QtCore.QCoreApplication.translate
        NetWorkMonitor.setWindowTitle(_translate("NetWorkMonitor", "NetWorkMonitor"))
        self.startBtn.setText(_translate("NetWorkMonitor", "Start Ping"))
        self.checkLogBtn.setText(_translate("NetWorkMonitor", "Log"))
        self.host_fixture1.setText(_translate("NetWorkMonitor", "169.254.1.32"))
        self.host_gh.setText(_translate("NetWorkMonitor", "null"))
        self.stopBtn.setText(_translate("NetWorkMonitor", "Stop"))
        self.host_fixture2.setText(_translate("NetWorkMonitor", "169.254.1.34"))
        self.label.setText(_translate("NetWorkMonitor", "V0.0.1 ©PRM "))
        self.label_2.setText(_translate("NetWorkMonitor", "Fixture1"))
        self.label_3.setText(_translate("NetWorkMonitor", "Fixture2"))
        self.label_4.setText(_translate("NetWorkMonitor", "GroundHog"))
